version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379

  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_init:/var/lib/postgresql/data
    environment:      
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  benchmark_service:
    build: .
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - ./:/app
    depends_on:
      - redis
      - postgres
      - randomiser_service
    command: ["uvicorn", "src.benchmark_service.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

  randomiser_service:
    build: .
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - ./:/app
    depends_on:
      - redis
      - postgres
    command: ["uvicorn", "src.randomiser_service.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${DASHBOARD_PASSWORD}
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    volumes:
      - grafana_init:/var/lib/grafana
    depends_on:
      - postgres 

volumes:
  postgres_init:
    driver: local
  grafana_init:
