apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-benchmark-service
spec:
  type: {{ .Values.benchmarkService.service.type }}
  ports:
    - port: {{ .Values.benchmarkService.service.port }}
      targetPort: 8000
  selector:
    app: benchmark-service
