apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-benchmark-service
spec:
  replicas: {{ .Values.benchmarkService.replicaCount }}
  selector:
    matchLabels:
      app: benchmark-service
  template:
    metadata:
      labels:
        app: benchmark-service
    spec:
      containers:
        - name: benchmark-service
          image: "{{ .Values.benchmarkService.image.repository }}:{{ .Values.benchmarkService.image.tag }}"
          imagePullPolicy: {{ .Values.benchmarkService.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
            - secretRef:
                name: {{ .Release.Name }}-secrets
