apiVersion: v2
name: llm-benchmark
description: A Helm chart for LLM Benchmark Tool
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: 12.1.6
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 17.10.1
    repository: https://charts.bitnami.com/bitnami
