name: Build, Test, and Deploy 🚀

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run Tests
        run: |
          poetry run pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build 

    steps:
      - uses: actions/checkout@v4

      - name: Set up Environment Variables 📜
        run: echo "KUBECONFIG=${{ secrets.KUBECONFIG }}" >> $GITHUB_ENV

      - name: Execute Deploy 🚀
        run: |
          chmod +x ./hack.sh
          ./hack.sh \
            ${{ secrets.ACCESS_KEY }} \
            ${{ secrets.SECRET_KEY }} \
            ${{ secrets.AWS_DEFAULT_REGION }} \
            ${{ secrets.AWS_ECR_ACCOUNT_URL }} \
            ${{ secrets.KUBECONFIG }} \
            ${{ secrets.CLUSTER }}
